### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by alaamohamed2** [shayantaherian/Object_Detection_Carla#1]
I got Error while running code can you help me with it please?
Traceback (most recent call last):
  File "Object_Detection1.py", line 958, in <module>
    main()
  File "Object_Detection1.py", line 951, in main
    game_loop(args)
  File "Object_Detection1.py", line 859, in game_loop
    hud = HUD(args.width, args.height)
  File "Object_Detection1.py", line 377, in __init__
    self.help = HelpText(pygame.font.Font(mono, 24), width, height)
  File "Object_Detection1.py", line 537, in __init__
    lines = __doc__.split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Arunprakaash** [comment]
have you resolved this?

**Comment by shayantaherian** [comment]
It seems that the input image is None when running the script, meaning that pygame is not running properly, Have you tested the carla properly without using the detection algorithm?
