### ISSUE TITLE
`__doc__` is None @ Line:536

### ISSUE THREAD

**Issue by Ezharjan** [shayantaherian/Object_Detection_Carla#9]
### Problem
The `_doc_` is none, at [this line](https://github.com/shayantaherian/Object_Detection_Carla/blob/b6c221f8ddff9c12bf150a6a37652deeba36a432/Object_Detection.py#L536C1-L536C4) .

The whole error goes as follows:
```
(carlarl) alex@fst-computer:~/Documents/Carla913/PythonAPI$ python Object_Detection.py 
2024-04-06 17:06:59.822425: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-06 17:07:00.020578: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-06 17:07:00.037375: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib:/usr/local/cuda/lib64:
2024-04-06 17:07:00.037404: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-04-06 17:07:00.563955: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib:/usr/local/cuda/lib64:
2024-04-06 17:07:00.564120: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib:/usr/local/cuda/lib64:
2024-04-06 17:07:00.564153: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
pygame 2.5.2 (SDL 2.28.2, Python 3.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 127.0.0.1:7963
None
Traceback (most recent call last):
  File "Object_Detection.py", line 1035, in <module>
    main()
  File "Object_Detection.py", line 1028, in main
    game_loop(args)
  File "Object_Detection.py", line 929, in game_loop
    hud = HUD(args.width, args.height)
  File "Object_Detection.py", line 390, in __init__
    self.help = HelpText(pygame.font.Font(mono, 24), width, height)
  File "Object_Detection.py", line 571, in __init__
    lines = __doc__.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```

### Env
1. carla==0.9.13
2. Python==3.7.16

**Comment by caoding1996** [comment]
same issue

**Comment by shayantaherian** [comment]
use the following command instead
lines = (__doc__ or "").split("\n")
